os:
  - linux
  - osx
osx_image: xcode7.3
sudo: required
language: node_js
node_js:
  - "4.4.6"
  - "6.2.2"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 5g -volname build build.dmg ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then hdiutil attach build.dmg ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp -r . /Volumes/build ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd /Volumes/build ; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install binutils ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-sed --with-default-names ; fi
script:
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run unbuild ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run build ; fi
