#!/usr/bin/env bash

set +h

#
# Applies OSX "dependencies" needed to compile the linux kernel
#

if [[ $(uname -s) = "Darwin" ]]; then
  command -v brew >/dev/null ||
  (
    echo "Brew is not installed" &&
    echo "Visit http://brew.sh/ for more information" &&
    exit 40
  )

  brew install gnu-sed --with-default-names || exit $?
fi
