#!/usr/bin/env bash

source scripts/adjustEnvVars.sh


#
# Define steps paths
#

PRODUCTS=(bin lib libexec share *-nodeos-linux-musl)
PREBUILD=prebuilds/$KERNEL_NAME-$NODE_ARCH.tar.gz


# Clean products previously to create them
rm -rf ${PRODUCTS[@]} || exit 11


#
# Build cross toolchain for all supported platforms
#

PLATFORM=pc_qemu_32 npm run build || exit 1
PLATFORM=pc_qemu_64 npm run build || exit 2


#
# Pack toolchain in a node-gyp compatible way
#

STEP_DIR=$PREBUILD

mkdir -p prebuilds                          &&
tar -cf - ${PRODUCTS[@]} | gzip > $PREBUILD || err 12


#
# Upload release to GitHub
#

if [ "$GITHUB_TOKEN" ]; then
  prebuild --upload-all $GITHUB_TOKEN || exit 20
fi
