#!/usr/bin/env bash

set -o pipefail


DOWNLOAD=https://github.com/NodeOS/nodeos-cross-toolchain/releases/download/v{version}/{platform}-{arch}.tar.gz
SYMLINKS=(addr2line ar as c++filt elfedit gprof ld ld.bfd nm objcopy objdump \
          ranlib readelf size strings strip c++ cpp g++ gcc gcov gcov-tool)


#
# Download or build cross-toolchain
#

prebuild-install -d $DOWNLOAD || npm run build || exit 10


# If host platform is not based on musl, don't create un-prefixed symlinks
readlink /lib/ld-linux.so.2 | grep musl || exit 0


#
# Update the bypass symbolic links to point to the native platform binaries
#

PLATFORM=
CPU=

source scripts/adjustEnvVars.sh || exit $?

mkdir -p bin || exit 20

for i in "${SYMLINKS[@]}"
do
  ln -sf $TARGET-$i bin/$i || exit 21
done
