#!/usr-env bash

#
# Symbolic links for native platform binaries
#

PLATFORM=
CPU=

source scripts/adjustEnvVars.sh || exit $?

mkdir -p bin || exit 10

# Binutils
ln -sf $TARGET-addr2line addr2line &&
       $TARGET-ar        ar        &&
       $TARGET-as        as        &&
       $TARGET-c++filt   c++filt   &&
       $TARGET-elfedit   elfedit   &&
       $TARGET-gprof     gprof     &&
       $TARGET-ld        ld        &&
       $TARGET-ld.bfd    ld.bfd    &&
       $TARGET-nm        nm        &&
       $TARGET-objcopy   objcopy   &&
       $TARGET-objdump   objdump   &&
       $TARGET-ranlib    ranlib    &&
       $TARGET-readelf   readelf   &&
       $TARGET-size      size      &&
       $TARGET-strings   strings   &&
       $TARGET-strip     strip     || exit 11

# GCC
ln -sf $TARGET-c++       c++       &&
       $TARGET-cpp       cpp       &&
       $TARGET-g++       g++       &&
       $TARGET-gcc       gcc       &&
       $TARGET-gcov      gcov      &&
       $TARGET-gcov-tool gcov-tool || exit 12
