#!/usr/bin/env node

const fs = require('fs')


const DIR = 'bin'
const bins = Object.keys(require('../package.json').bin)
const bypass = fs.readFileSync('bypass.js')


// http://stackoverflow.com/a/34597104/586382
// NPM will run prepublish script after `npm install` (https://docs.npmjs.com/misc/scripts)
// This ensures that when script is executed using `npm *` it is run only when the command is `npm publish`.
const npm_config_argv = process.env.npm_config_argv
if(npm_config_argv && JSON.parse(npm_config_argv).original[0] === 'publish')
  fs.mkdir(DIR, function(err)
  {
    if(err && err.code !== 'EEXIST') throw err

    fs.readdir(DIR, function(err, files)
    {
      if(err) throw err

      // Delete all files in the `bin` folder
      files.forEach(function(file)
      {
        fs.unlinkSync(DIR+'/'+file)
      })

      // Re-create the symlinks stubs
      bins.forEach(function(file)
      {
        fs.writeFileSync(DIR+'/'+file, bypass, {mode: 0o555})
      })
    })
  })
