#!/usr/bin/env node

/**
 * Reset the generic bin symlinks before publishing to npm so they point to the
 * native platform libraries
 */

const fs = require('fs')


// http://stackoverflow.com/a/34597104/586382
// By design, NPM will run prepublish script after `npm install` (see
// [npm docs](https://docs.npmjs.com/misc/scripts))
// This trick ensures that when script is executed using `npm <whatever>` it is
// run only when the command is `npm publish`.
const npm_config_argv = process.env.npm_config_argv
if(npm_config_argv && JSON.parse(npm_config_argv).original[0] === 'publish'
|| process.argv[2] === '--force')
{
  const DIR = 'bin'

  fs.mkdir(DIR, function(err)
  {
    if(err && err.code !== 'EEXIST') throw err

    fs.readFile('resources/bypass.js', function(err, bypass)
    {
      if(err) throw err

      // Re-create the symlinks stubs
      Object.keys(require('../package.json').bin).forEach(function(file)
      {
        fs.writeFileSync(DIR+'/'+file, bypass, {mode: 0o755})
      })
    })
  })
}
