#!/usr/bin/env bash


source scripts/adjustEnvVars.sh || exit $?


LIBC="/lib/ld-musl-$CPU_PORT.so.1"
PATH=`pwd`/bin:$PATH

(
  mkdir -p build || exit 1

  cp resources/dummy.c build || exit 2

  cd build || exit 3

  $TARGET-gcc dummy.c                      || exit 4
  $TARGET-readelf -l a.out | grep -q $LIBC || exit 5
  rm dummy.c a.out                         || exit 6
) || exit $?
